version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "jpenzell"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      - dependency-name: "torch"
        versions: ["< 2.0.0"]
      - dependency-name: "transformers"
        versions: ["< 4.0.0"] 